// generated by scripts/fetch_members.py from 48pedia.org
window.AKB_GROUPS = [
 {
  "label": "1期生",
  "members": [
   {
    "id": "m8393c0805d",
    "name": "板野友美",
    "kana": "いたの ともみ",
    "nick": "ともちん",
    "status": "former",
    "end": "2013.08.27",
    "img": true
   },
   {
    "id": "mae7a58749f",
    "name": "宇佐美友紀",
    "kana": "うさみ ゆき",
    "nick": "ゆっき～",
    "status": "former",
    "end": "2006.03.31",
    "img": true
   },
   {
    "id": "m2ba60e0b41",
    "name": "浦野一美",
    "kana": "うらの かずみ",
    "nick": "CinDy",
    "status": "former",
    "end": "2010.04.16",
    "img": true
   },
   {
    "id": "m851d800f25",
    "name": "大江朝美",
    "kana": "おおえ ともみ",
    "nick": "おーいぇ",
    "status": "former",
    "end": "2008.11.23",
    "img": true
   },
   {
    "id": "m01a4b0ab84",
    "name": "大島麻衣",
    "kana": "おおしま まい",
    "nick": "まいまい",
    "status": "former",
    "end": "2009.04.26",
    "img": true
   },
   {
    "id": "m629d582c1f",
    "name": "折井あゆみ",
    "kana": "おりい あゆみ",
    "nick": "あゆ姉",
    "status": "former",
    "end": "2007.01.25",
    "img": true
   },
   {
    "id": "m0711cee99f",
    "name": "川崎希",
    "kana": "かわさき のぞみ",
    "nick": "のぞフィス",
    "status": "former",
    "end": "2009.02.27",
    "img": true
   },
   {
    "id": "mc4a5044789",
    "name": "小嶋陽菜",
    "kana": "こじま はるな",
    "nick": "こじはる",
    "status": "former",
    "end": "2017.04.19",
    "img": true
   },
   {
    "id": "m3c9f643e4e",
    "name": "駒谷仁美",
    "kana": "こまたに ひとみ",
    "nick": "ひぃちゃん",
    "status": "former",
    "end": "2008.11.23",
    "img": true
   },
   {
    "id": "mc85c828af6",
    "name": "佐藤由加理",
    "kana": "さとう ゆかり",
    "nick": "ゆかりん",
    "status": "former",
    "end": "2010.05.27",
    "img": true
   },
   {
    "id": "m00d0603716",
    "name": "高橋みなみ",
    "kana": "たかはし みなみ",
    "nick": "たかみな",
    "status": "former",
    "end": "2016.04.08",
    "img": true
   },
   {
    "id": "mb568cdd433",
    "name": "戸島花",
    "kana": "とじま はな",
    "nick": "はな",
    "status": "former",
    "end": "2008.11.23",
    "img": true
   },
   {
    "id": "m7b733904fe",
    "name": "中西里菜",
    "kana": "なかにし りな",
    "nick": "りなてぃん",
    "status": "former",
    "end": "2008.11.23",
    "img": true
   },
   {
    "id": "m4084cb80e5",
    "name": "成田梨紗",
    "kana": "なりた りさ",
    "nick": "りさ",
    "status": "former",
    "end": "2008.11.23",
    "img": true
   },
   {
    "id": "mf9c80c0c58",
    "name": "平嶋夏海",
    "kana": "ひらじま なつみ",
    "nick": "なっちゃん",
    "status": "former",
    "end": "2012.02.05",
    "img": true
   },
   {
    "id": "mc39ff3ea5c",
    "name": "星野みちる",
    "kana": "ほしの みちる",
    "nick": "ちるちる",
    "status": "former",
    "end": "2007.06.26",
    "img": true
   },
   {
    "id": "m3dbe559b39",
    "name": "前田敦子",
    "kana": "まえだ あつこ",
    "nick": "あっちゃん",
    "status": "former",
    "end": "2012.08.27",
    "img": true
   },
   {
    "id": "ma1168427d4",
    "name": "増山加弥乃",
    "kana": "ますやま かやの",
    "nick": "かやの",
    "status": "former",
    "end": "2007.11.30",
    "img": true
   },
   {
    "id": "m42ba0d1ac2",
    "name": "峯岸みなみ",
    "kana": "みねぎし みなみ",
    "nick": "みいちゃん",
    "status": "former",
    "end": "2021.05.29",
    "img": true
   },
   {
    "id": "m80ee1bb11c",
    "name": "渡邊志穂",
    "kana": "わたなべ しほ",
    "nick": "しほ",
    "status": "former",
    "end": "2007.10.02",
    "img": true
   }
  ]
 },
 {
  "label": "1.5期生",
  "members": [
   {
    "id": "m554f3f3f7c",
    "name": "篠田麻里子",
    "kana": "しのだ まりこ",
    "nick": "まりこ",
    "status": "former",
    "end": "2013.07.22",
    "img": true
   }
  ]
 },
 {
  "label": "2期生",
  "members": [
   {
    "id": "m9431b2ac4c",
    "name": "秋元才加",
    "kana": "あきもと さやか",
    "nick": "さやか",
    "status": "former",
    "end": "2013.08.28",
    "img": true
   },
   {
    "id": "m0575758675",
    "name": "今井優",
    "kana": "いまい ゆう",
    "nick": "ゆう",
    "status": "former",
    "end": "2007.06.22",
    "img": true
   },
   {
    "id": "m1e209eeb08",
    "name": "上村彩子",
    "kana": "うえむら あやこ",
    "nick": "あやたん",
    "status": "former",
    "end": "2006.06.17",
    "img": true
   },
   {
    "id": "m60c3483f7c",
    "name": "梅田彩佳",
    "kana": "うめだ あやか",
    "nick": "うめちゃん",
    "status": "former",
    "end": "2014.04.23",
    "img": true
   },
   {
    "id": "m3ba08e033b",
    "name": "大島優子",
    "kana": "おおしま ゆうこ",
    "nick": "ゆうこ",
    "status": "former",
    "end": "2014.06.09",
    "img": true
   },
   {
    "id": "mbbde5ee542",
    "name": "大堀恵",
    "kana": "おおほり めぐみ",
    "nick": "めーたん",
    "status": "former",
    "end": "2010.02.21",
    "img": true
   },
   {
    "id": "m3fbeb80273",
    "name": "奥真奈美",
    "kana": "おく まなみ",
    "nick": "まぁちゃん",
    "status": "former",
    "end": "2011.06.19",
    "img": true
   },
   {
    "id": "m6b9d2533f4",
    "name": "小野恵令奈",
    "kana": "おの えれな",
    "nick": "えれぴょん",
    "status": "former",
    "end": "2010.09.27",
    "img": true
   },
   {
    "id": "m57ee3bc3fd",
    "name": "河西智美",
    "kana": "かさい ともみ",
    "nick": "とも～み",
    "status": "former",
    "end": "2013.05.03",
    "img": true
   },
   {
    "id": "mea9d9a2a69",
    "name": "小林香菜",
    "kana": "こばやし かな",
    "nick": "かな",
    "status": "former",
    "end": "2016.03.31",
    "img": true
   },
   {
    "id": "m4ce5969b03",
    "name": "佐藤夏希",
    "kana": "さとう なつき",
    "nick": "Nなっち",
    "status": "former",
    "end": "2012.11.30",
    "img": true
   },
   {
    "id": "mcbe5818e22",
    "name": "高田彩奈",
    "kana": "たかだ あやな",
    "nick": "あやな",
    "status": "former",
    "end": "2007.06.22",
    "img": true
   },
   {
    "id": "m837dd982ae",
    "name": "野呂佳代",
    "kana": "のろ かよ",
    "nick": "ノンティ",
    "status": "former",
    "end": "2010.02.21",
    "img": true
   },
   {
    "id": "m67970e17a9",
    "name": "早野薫",
    "kana": "はやの かおる",
    "nick": "かおりん",
    "status": "former",
    "end": "2009.04.26",
    "img": true
   },
   {
    "id": "md91bac4669",
    "name": "増田有華",
    "kana": "ますだ ゆか",
    "nick": "ゆったん",
    "status": "former",
    "end": "2012.12.17",
    "img": true
   },
   {
    "id": "ma038d6fe11",
    "name": "松原夏海",
    "kana": "まつばら なつみ",
    "nick": "なっつみぃ",
    "status": "former",
    "end": "2013.07.07",
    "img": true
   },
   {
    "id": "mc2115f4357",
    "name": "宮澤佐江",
    "kana": "みやざわ さえ",
    "nick": "さえ",
    "status": "former",
    "end": "2013.06.24",
    "img": true
   }
  ]
 },
 {
  "label": "3期生",
  "members": [
   {
    "id": "m8ff408db63",
    "name": "磯怜奈",
    "kana": "いそ れいな",
    "nick": "",
    "status": "former",
    "end": "2006.12.19",
    "img": true
   },
   {
    "id": "m696b838edb",
    "name": "井上奈瑠",
    "kana": "いのうえ なる",
    "nick": "なるぽん",
    "status": "former",
    "end": "2008.09.29",
    "img": true
   },
   {
    "id": "mf3eba033c5",
    "name": "多田愛佳",
    "kana": "おおた あいか",
    "nick": "らぶたん",
    "status": "former",
    "end": "2012.10.31",
    "img": true
   },
   {
    "id": "md8741be2d9",
    "name": "大塚亜季",
    "kana": "おおつか あき",
    "nick": "",
    "status": "former",
    "end": "2006.12.19",
    "img": true
   },
   {
    "id": "m4ff5e7f3b7",
    "name": "柏木由紀",
    "kana": "かしわぎ ゆき",
    "nick": "ゆきりん",
    "status": "former",
    "end": "2024.04.30",
    "img": true
   },
   {
    "id": "m2fae710269",
    "name": "片山陽加",
    "kana": "かたやま はるか",
    "nick": "はーちゃん",
    "status": "former",
    "end": "2014.09.29",
    "img": true
   },
   {
    "id": "ma96468ddfa",
    "name": "早乙女美樹",
    "kana": "さおとめ みき",
    "nick": "みきポム",
    "status": "former",
    "end": "2009.04.18",
    "img": true
   },
   {
    "id": "m6da0b87563",
    "name": "坂田涼",
    "kana": "さかた りょう",
    "nick": "",
    "status": "former",
    "end": "2006.12.19",
    "img": true
   },
   {
    "id": "mb6e80d55bb",
    "name": "田名部生来",
    "kana": "たなべ みく",
    "nick": "たなみん",
    "status": "former",
    "end": "2017.07.23",
    "img": true
   },
   {
    "id": "m67a16eafe6",
    "name": "仲川遥香",
    "kana": "なかがわ はるか",
    "nick": "はるか",
    "status": "former",
    "end": "2012.10.31",
    "img": true
   },
   {
    "id": "mfbd235d5a4",
    "name": "仲谷明香",
    "kana": "なかや さやか",
    "nick": "なかやん",
    "status": "former",
    "end": "2013.03.06",
    "img": true
   },
   {
    "id": "m83c8b17758",
    "name": "野口玲菜",
    "kana": "のぐち れいな",
    "nick": "ぐっさん",
    "status": "former",
    "end": "2009.02.01",
    "img": true
   },
   {
    "id": "mab822e8756",
    "name": "藤島マリアチカ",
    "kana": "ふじしま マリアチカ",
    "nick": "",
    "status": "former",
    "end": "2006.12.19",
    "img": true
   },
   {
    "id": "m048142f73d",
    "name": "堀江聖夏",
    "kana": "ほりえ みな",
    "nick": "",
    "status": "former",
    "end": "2006.12.19",
    "img": true
   },
   {
    "id": "m95f40a0b7b",
    "name": "松岡由紀",
    "kana": "まつおか ゆき",
    "nick": "まつゆき",
    "status": "former",
    "end": "2009.02.01",
    "img": true
   },
   {
    "id": "m794d3abef9",
    "name": "米沢瑠美",
    "kana": "よねざわ るみ",
    "nick": "よねちゃん",
    "status": "former",
    "end": "2012.02.05",
    "img": true
   },
   {
    "id": "m64c32528f0",
    "name": "渡辺麻友",
    "kana": "わたなべ まゆ",
    "nick": "まゆゆ",
    "status": "former",
    "end": "2017.12.31",
    "img": true
   }
  ]
 },
 {
  "label": "4期生",
  "members": [
   {
    "id": "m8e5c86a9f5",
    "name": "飯沼友里奈",
    "kana": "いいぬま ゆりな",
    "nick": "",
    "status": "former",
    "end": "2007.11.15",
    "img": true
   },
   {
    "id": "mbeed3dc3a0",
    "name": "瓜屋茜",
    "kana": "うりや あかね",
    "nick": "うりゃ",
    "status": "former",
    "end": "2009.04.26",
    "img": true
   },
   {
    "id": "m136074e49f",
    "name": "大家志津香",
    "kana": "おおや しづか",
    "nick": "しいちゃん",
    "status": "former",
    "end": "2021.12.29",
    "img": true
   },
   {
    "id": "m2fbcaf3557",
    "name": "金子智美",
    "kana": "かねこ さとみ",
    "nick": "",
    "status": "former",
    "end": "2007.11.15",
    "img": true
   },
   {
    "id": "m57e3742184",
    "name": "倉持明日香",
    "kana": "くらもち あすか",
    "nick": "もっちぃ",
    "status": "former",
    "end": "2015.08.17",
    "img": true
   },
   {
    "id": "m851b321e89",
    "name": "小塚里菜",
    "kana": "こづか りな",
    "nick": "",
    "status": "former",
    "end": "2007.11.15",
    "img": true
   },
   {
    "id": "m8ced0f38a5",
    "name": "佐藤亜美菜",
    "kana": "さとう あみな",
    "nick": "あみな",
    "status": "former",
    "end": "2014.06.29",
    "img": true
   },
   {
    "id": "m03f612264a",
    "name": "鈴木菜絵",
    "kana": "すずき なえ",
    "nick": "",
    "status": "former",
    "end": "2009.01.18",
    "img": true
   },
   {
    "id": "m574312ba30",
    "name": "出口陽",
    "kana": "でぐち あき",
    "nick": "",
    "status": "former",
    "end": "2007.11.26",
    "img": true
   },
   {
    "id": "m9909eff11a",
    "name": "中田ちさと",
    "kana": "なかた ちさと",
    "nick": "ちぃちゃん",
    "status": "former",
    "end": "2017.04.24",
    "img": true
   },
   {
    "id": "mcf2027bc84",
    "name": "中西優香",
    "kana": "なかにし ゆうか",
    "nick": "",
    "status": "former",
    "end": "2008.08.26",
    "img": true
   },
   {
    "id": "mff65dab2be",
    "name": "成瀬理沙",
    "kana": "なるせ りさ",
    "nick": "なるる",
    "status": "former",
    "end": "2009.05.24",
    "img": true
   },
   {
    "id": "mac16a93ea1",
    "name": "藤江れいな",
    "kana": "ふじえ れいな",
    "nick": "れいにゃん",
    "status": "former",
    "end": "2014.04.23",
    "img": true
   },
   {
    "id": "m9d64a7e6c6",
    "name": "吉岡沙葵",
    "kana": "よしおか さき",
    "nick": "",
    "status": "former",
    "end": "2007.11.15",
    "img": true
   },
   {
    "id": "mb7d1942895",
    "name": "渡辺茉莉絵",
    "kana": "わたなべ まりえ",
    "nick": "",
    "status": "former",
    "end": "2007.11.15",
    "img": true
   }
  ]
 },
 {
  "label": "5期生",
  "members": [
   {
    "id": "mf0083f4772",
    "name": "有馬優茄",
    "kana": "ありま ゆか",
    "nick": "ありゃま",
    "status": "former",
    "end": "2009.01.18",
    "img": true
   },
   {
    "id": "m4ded9e73aa",
    "name": "石田晴香",
    "kana": "いしだ はるか",
    "nick": "はるきゃん",
    "status": "former",
    "end": "2016.06.05",
    "img": true
   },
   {
    "id": "mda0db6fd48",
    "name": "内田眞由美",
    "kana": "うちだ まゆみ",
    "nick": "内田さんウッチー",
    "status": "former",
    "end": "2015.10.25",
    "img": true
   },
   {
    "id": "m19f759dd0e",
    "name": "北原里英",
    "kana": "きたはら りえ",
    "nick": "きたりえ",
    "status": "former",
    "end": "2015.08.26",
    "img": true
   },
   {
    "id": "ma85bc9bb5f",
    "name": "小原春香",
    "kana": "こはら はるか",
    "nick": "はるちゃん",
    "status": "former",
    "end": "2010.04.16",
    "img": true
   },
   {
    "id": "m8fc71b5ebc",
    "name": "指原莉乃",
    "kana": "さしはら りの",
    "nick": "さっしー",
    "status": "former",
    "end": "2012.06.16",
    "img": true
   },
   {
    "id": "mfeb9540951",
    "name": "近野莉菜",
    "kana": "ちかの りな",
    "nick": "チカリーナ",
    "status": "former",
    "end": "2014.04.16",
    "img": true
   },
   {
    "id": "md02f1c2b54",
    "name": "冨田麻友",
    "kana": "とみた まゆ",
    "nick": "まゆとみー",
    "status": "former",
    "end": "2009.01.18",
    "img": true
   },
   {
    "id": "m47708b1847",
    "name": "中塚智実",
    "kana": "なかつか ともみ",
    "nick": "ともちゃん",
    "status": "former",
    "end": "2013.07.07",
    "img": true
   },
   {
    "id": "m5fb7c5e4c8",
    "name": "仁藤萌乃",
    "kana": "にとう もえの",
    "nick": "もえの",
    "status": "former",
    "end": "2013.04.28",
    "img": true
   },
   {
    "id": "m60ff6a0678",
    "name": "畑山亜梨紗",
    "kana": "はたやま ありさ",
    "nick": "ありりんありさ",
    "status": "former",
    "end": "2009.01.19",
    "img": true
   },
   {
    "id": "m230459a204",
    "name": "宮崎美穂",
    "kana": "みやざき みほ",
    "nick": "みゃお",
    "status": "former",
    "end": "2022.04.15",
    "img": true
   },
   {
    "id": "ma14e7d357c",
    "name": "山田みずき",
    "kana": "やまだ みずき",
    "nick": "",
    "status": "former",
    "end": "2007.12.08",
    "img": true
   }
  ]
 },
 {
  "label": "6期生",
  "members": [
   {
    "id": "m5eabf742b9",
    "name": "片野友里恵",
    "kana": "かたの ゆりえ",
    "nick": "ゆりちゃん",
    "status": "former",
    "end": "2008.08.31",
    "img": true
   },
   {
    "id": "m3aecd03c28",
    "name": "高城亜樹",
    "kana": "たかじょう あき",
    "nick": "あきちゃ",
    "status": "former",
    "end": "2016.05.01",
    "img": true
   },
   {
    "id": "m4514d1c790",
    "name": "西澤沙羅",
    "kana": "にしざわ さら",
    "nick": "",
    "status": "former",
    "end": "2008.07.31",
    "img": true
   },
   {
    "id": "m74a279fa70",
    "name": "野中美郷",
    "kana": "のなか みさと",
    "nick": "みちゃ",
    "status": "former",
    "end": "2014.09.23",
    "img": true
   }
  ]
 },
 {
  "label": "7期生",
  "members": [
   {
    "id": "mc62b87cd62",
    "name": "石黒莉美",
    "kana": "いしぐろ れみ",
    "nick": "",
    "status": "former",
    "end": "2009.01.16",
    "img": true
   },
   {
    "id": "meef41be845",
    "name": "岩佐美咲",
    "kana": "いわさ みさき",
    "nick": "わさみん",
    "status": "former",
    "end": "2016.05.21",
    "img": true
   },
   {
    "id": "m7bb85ae686",
    "name": "上遠野瑞穂",
    "kana": "かとおの みずほ",
    "nick": "みーたん",
    "status": "former",
    "end": "2009.06.09",
    "img": true
   },
   {
    "id": "m2ade342b50",
    "name": "菊地あやか",
    "kana": "きくち あやか",
    "nick": "あやりん",
    "status": "former",
    "end": "2014.09.23",
    "img": true
   },
   {
    "id": "mb550bb0e13",
    "name": "小森美果",
    "kana": "こもり みか",
    "nick": "こもりん",
    "status": "former",
    "end": "2013.07.07",
    "img": true
   },
   {
    "id": "m5fc97e36eb",
    "name": "佐藤すみれ",
    "kana": "さとう すみれ",
    "nick": "すーちゃん",
    "status": "former",
    "end": "2014.04.21",
    "img": true
   },
   {
    "id": "me64b4bb3ba",
    "name": "鈴木まりや",
    "kana": "すずき まりや",
    "nick": "まりやんぬ",
    "status": "former",
    "end": "2017.06.10",
    "img": true
   },
   {
    "id": "m3e0203991a",
    "name": "林彩乃",
    "kana": "はやし あやの",
    "nick": "あやのん",
    "status": "former",
    "end": "2009.07.18",
    "img": true
   },
   {
    "id": "mc503dcc2ec",
    "name": "前田亜美",
    "kana": "まえだ あみ",
    "nick": "あーみん",
    "status": "former",
    "end": "2016.08.29",
    "img": true
   },
   {
    "id": "ma2c60241ac",
    "name": "松井咲子",
    "kana": "まつい さきこ",
    "nick": "さきこ",
    "status": "former",
    "end": "2015.08.09",
    "img": true
   }
  ]
 },
 {
  "label": "8期生",
  "members": [
   {
    "id": "m7bff579c6a",
    "name": "浅居円",
    "kana": "あさい まどか",
    "nick": "まりん",
    "status": "former",
    "end": "2009.12.04",
    "img": true
   },
   {
    "id": "m02fda111e0",
    "name": "石井彩夏",
    "kana": "いしい あやか",
    "nick": "あやめろ",
    "status": "former",
    "end": "2009.12.04",
    "img": true
   },
   {
    "id": "mcb93c85742",
    "name": "石部郁",
    "kana": "いしべ あや",
    "nick": "あやにゃん",
    "status": "former",
    "end": "2009.12.04",
    "img": true
   },
   {
    "id": "mc08c112be7",
    "name": "今井悠理枝",
    "kana": "いまい ゆりえ",
    "nick": "ゆりはむ",
    "status": "former",
    "end": "2010.02.01",
    "img": true
   },
   {
    "id": "m564151051c",
    "name": "植木あさ香",
    "kana": "うえき あさか",
    "nick": "あさぽん",
    "status": "former",
    "end": "2010.07.06",
    "img": true
   },
   {
    "id": "m9139bd7fb1",
    "name": "郭グレース",
    "kana": "かく グレース",
    "nick": "ぐーたん",
    "status": "former",
    "end": "2009.12.04",
    "img": true
   },
   {
    "id": "me92faca060",
    "name": "小松瑞希",
    "kana": "こまつ みずき",
    "nick": "みっきー",
    "status": "former",
    "end": "2009.07.14",
    "img": true
   },
   {
    "id": "me297639514",
    "name": "小水七海",
    "kana": "こみず ななみ",
    "nick": "こみたん",
    "status": "former",
    "end": "2009.12.04",
    "img": true
   },
   {
    "id": "maffee3f9d7",
    "name": "坂本莉央",
    "kana": "さかもと りお",
    "nick": "りっちゃん",
    "status": "former",
    "end": "2009.12.04",
    "img": true
   },
   {
    "id": "mc5ae97faad",
    "name": "佐野友里子",
    "kana": "さの ゆりこ",
    "nick": "ゆりりん",
    "status": "former",
    "end": "2010.10.05",
    "img": true
   },
   {
    "id": "m63ad331e13",
    "name": "杉山未来",
    "kana": "すぎやま みく",
    "nick": "",
    "status": "former",
    "end": "2009.12.04",
    "img": true
   },
   {
    "id": "m0dbb2362bd",
    "name": "冨手麻妙",
    "kana": "とみて あみ",
    "nick": "まみょん",
    "status": "former",
    "end": "2009.12.04",
    "img": true
   },
   {
    "id": "m27ef4ccd4f",
    "name": "西川七海",
    "kana": "にしかわ ななみ",
    "nick": "ななみん",
    "status": "former",
    "end": "2009.07.25",
    "img": true
   },
   {
    "id": "m2dde861dda",
    "name": "三木にこる",
    "kana": "みき にこる",
    "nick": "にこるん",
    "status": "former",
    "end": "2009.12.04",
    "img": true
   },
   {
    "id": "m636f6fbc7e",
    "name": "村中聡美",
    "kana": "むらなか さとみ",
    "nick": "さとみん",
    "status": "former",
    "end": "2009.12.04",
    "img": true
   }
  ]
 },
 {
  "label": "9期生",
  "members": [
   {
    "id": "mc51242a7d9",
    "name": "石黒貴己",
    "kana": "いしぐろ あつき",
    "nick": "あっきー",
    "status": "former",
    "end": "2010.06.20",
    "img": true
   },
   {
    "id": "mb17208bf96",
    "name": "伊藤彩夏",
    "kana": "いとう あやか",
    "nick": "あやぽん",
    "status": "former",
    "end": "2010.01.06",
    "img": true
   },
   {
    "id": "m7e6c50e7fb",
    "name": "大場美奈",
    "kana": "おおば みな",
    "nick": "みなるん",
    "status": "former",
    "end": "2014.04.23",
    "img": true
   },
   {
    "id": "mddb8ff6333",
    "name": "絹本桃子",
    "kana": "きぬもと ももこ",
    "nick": "ももちん",
    "status": "former",
    "end": "2010.06.20",
    "img": true
   },
   {
    "id": "m71929abeb5",
    "name": "島崎遥香",
    "kana": "しまざき はるか",
    "nick": "ぱるる",
    "status": "former",
    "end": "2016.12.31",
    "img": true
   },
   {
    "id": "ma0b03d2869",
    "name": "島田晴香",
    "kana": "しまだ はるか",
    "nick": "はるぅしまだ",
    "status": "former",
    "end": "2017.11.13",
    "img": true
   },
   {
    "id": "md0e3e19c28",
    "name": "高松恵理",
    "kana": "たかまつ えり",
    "nick": "えりりん",
    "status": "former",
    "end": "2010.06.20",
    "img": true
   },
   {
    "id": "m53ed8d2508",
    "name": "竹内美宥",
    "kana": "たけうち みゆ",
    "nick": "みゆみゆ",
    "status": "former",
    "end": "2019.05.06",
    "img": true
   },
   {
    "id": "md453e821a9",
    "name": "中村麻里子",
    "kana": "なかむら まりこ",
    "nick": "こまり",
    "status": "former",
    "end": "2017.03.30",
    "img": true
   },
   {
    "id": "mf610a9d23d",
    "name": "永尾まりや",
    "kana": "ながお まりや",
    "nick": "まりやまりやぎ",
    "status": "former",
    "end": "2016.05.01",
    "img": true
   },
   {
    "id": "m2a0e9380c3",
    "name": "藤本紗羅",
    "kana": "ふじもと さら",
    "nick": "おさら",
    "status": "former",
    "end": "2010.06.20",
    "img": true
   },
   {
    "id": "mc24236693a",
    "name": "森杏奈",
    "kana": "もり あんな",
    "nick": "なんちゃん",
    "status": "former",
    "end": "2011.09.02",
    "img": true
   },
   {
    "id": "mf17a7c90dc",
    "name": "山内鈴蘭",
    "kana": "やまうち すずらん",
    "nick": "らんらん",
    "status": "former",
    "end": "2014.04.23",
    "img": true
   },
   {
    "id": "mdd6413e287",
    "name": "横山由依",
    "kana": "よこやま ゆい",
    "nick": "ゆいはん",
    "status": "former",
    "end": "2021.12.09",
    "img": true
   }
  ]
 },
 {
  "label": "10期生",
  "members": [
   {
    "id": "m2a55302fc0",
    "name": "阿部マリア",
    "kana": "あべ マリア",
    "nick": "あべまる",
    "status": "former",
    "end": "2017.11.30",
    "img": true
   },
   {
    "id": "m2522d89e89",
    "name": "伊豆田莉奈",
    "kana": "いずた りな",
    "nick": "いずりな",
    "status": "former",
    "end": "2017.07.01",
    "img": true
   },
   {
    "id": "m02b159931b",
    "name": "市川美織",
    "kana": "いちかわ みおり",
    "nick": "みおりん",
    "status": "former",
    "end": "2014.04.23",
    "img": true
   },
   {
    "id": "mff2c4f1a7b",
    "name": "入山杏奈",
    "kana": "いりやま あんな",
    "nick": "あんにん",
    "status": "former",
    "end": "2022.03.17",
    "img": true
   },
   {
    "id": "m1c08e1a879",
    "name": "岩崎仁美",
    "kana": "いわさき ひとみ",
    "nick": "ひとみん",
    "status": "former",
    "end": "2010.10.05",
    "img": true
   },
   {
    "id": "mad8531a160",
    "name": "加藤玲奈",
    "kana": "かとう れな",
    "nick": "れなっち",
    "status": "former",
    "end": "2022.02.20",
    "img": true
   },
   {
    "id": "ma5547b6c7b",
    "name": "金沢有希",
    "kana": "かなざわ ゆうき",
    "nick": "ゆうきりんゆうちゃん",
    "status": "former",
    "end": "2011.02.20",
    "img": true
   },
   {
    "id": "mc62a16e7d4",
    "name": "小林茉里奈",
    "kana": "こばやし まりな",
    "nick": "まりんちゃん",
    "status": "former",
    "end": "2015.08.09",
    "img": true
   },
   {
    "id": "m410762c0d4",
    "name": "仲俣汐里",
    "kana": "なかまた しおり",
    "nick": "しおりん",
    "status": "former",
    "end": "2013.09.23",
    "img": true
   },
   {
    "id": "m523558022e",
    "name": "藤田奈那",
    "kana": "ふじた なな",
    "nick": "なぁな",
    "status": "former",
    "end": "2019.01.07",
    "img": true
   }
  ]
 },
 {
  "label": "11期生",
  "members": [
   {
    "id": "m52582f307a",
    "name": "牛窪紗良",
    "kana": "うしくぼ さら",
    "nick": "さらちゃん",
    "status": "former",
    "end": "2011.06.19",
    "img": true
   },
   {
    "id": "mffda5749e9",
    "name": "岡﨑ちなみ",
    "kana": "おかざき ちなみ",
    "nick": "",
    "status": "former",
    "end": "2010.10.27",
    "img": true
   },
   {
    "id": "m802e210927",
    "name": "川栄李奈",
    "kana": "かわえい りな",
    "nick": "りっちゃん",
    "status": "former",
    "end": "2015.08.04",
    "img": true
   },
   {
    "id": "m880591860f",
    "name": "川上麻里奈",
    "kana": "かわかみ まりな",
    "nick": "",
    "status": "former",
    "end": "2010.12.03",
    "img": true
   },
   {
    "id": "m07d084d9cf",
    "name": "小嶋菜月",
    "kana": "こじま なつき",
    "nick": "なっつん",
    "status": "former",
    "end": "2018.08.12",
    "img": true
   },
   {
    "id": "mb35e096795",
    "name": "鈴木紫帆里",
    "kana": "すずき しほり",
    "nick": "しほりん",
    "status": "former",
    "end": "2015.05.30",
    "img": true
   },
   {
    "id": "md3649b33ef",
    "name": "豊田早姫",
    "kana": "とよだ さき",
    "nick": "さきぴ",
    "status": "former",
    "end": "2010.10.23",
    "img": true
   },
   {
    "id": "m40c6260a37",
    "name": "名取稚菜",
    "kana": "なとり わかな",
    "nick": "わかにゃん",
    "status": "former",
    "end": "2016.02.14",
    "img": true
   },
   {
    "id": "m91e539f60f",
    "name": "森川彩香",
    "kana": "もりかわ あやか",
    "nick": "あーや",
    "status": "former",
    "end": "2015.05.30",
    "img": true
   },
   {
    "id": "m08e705f80f",
    "name": "山口菜有",
    "kana": "やまぐち なう",
    "nick": "なうちぃ",
    "status": "former",
    "end": "2011.06.19",
    "img": true
   }
  ]
 },
 {
  "label": "12期生",
  "members": [
   {
    "id": "m4770318d63",
    "name": "岩田華怜",
    "kana": "いわた かれん",
    "nick": "カレン",
    "status": "former",
    "end": "2016.05.21",
    "img": true
   },
   {
    "id": "m691d0a08fb",
    "name": "大森美優",
    "kana": "おおもり みゆう",
    "nick": "みゆぽん",
    "status": "former",
    "end": "2023.08.21",
    "img": true
   },
   {
    "id": "m61860394c7",
    "name": "佐々木優佳里",
    "kana": "ささき ゆかり",
    "nick": "ゆかるん",
    "status": "former",
    "end": "2024.02.23",
    "img": true
   },
   {
    "id": "m6bf25d30ee",
    "name": "鈴木里香",
    "kana": "すずき りか",
    "nick": "りかちゃん",
    "status": "former",
    "end": "2012.03.31",
    "img": true
   },
   {
    "id": "m05516a7331",
    "name": "高橋朱里",
    "kana": "たかはし じゅり",
    "nick": "じゅり",
    "status": "former",
    "end": "2019.05.06",
    "img": true
   },
   {
    "id": "mdfa81761ee",
    "name": "田野優花",
    "kana": "たの ゆうか",
    "nick": "たのちゃん",
    "status": "former",
    "end": "2018.08.12",
    "img": true
   },
   {
    "id": "mc16064f18d",
    "name": "平田梨奈",
    "kana": "ひらた りな",
    "nick": "ひらりー",
    "status": "former",
    "end": "2016.08.24",
    "img": true
   },
   {
    "id": "m79663226b1",
    "name": "武藤十夢",
    "kana": "むとう とむ",
    "nick": "とむ",
    "status": "former",
    "end": "2023.03.08",
    "img": true
   },
   {
    "id": "m369c2328fd",
    "name": "サイード横田絵玲奈",
    "kana": "サイードよこた えれな",
    "nick": "えれちゃん",
    "status": "former",
    "end": "2012.10.06",
    "img": true
   }
  ]
 },
 {
  "label": "12.5期生",
  "members": [
   {
    "id": "m155b7fcf70",
    "name": "江口愛実",
    "kana": "えぐち あいみ",
    "nick": "あいみ",
    "status": "former",
    "end": "2013.05.08",
    "img": true
   }
  ]
 },
 {
  "label": "13期生",
  "members": [
   {
    "id": "m14a7951a65",
    "name": "岩立沙穂",
    "kana": "いわたて さほ",
    "nick": "さっほー",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m4ccde91ced",
    "name": "相笠萌",
    "kana": "あいがさ もえ",
    "nick": "もえちゃん",
    "status": "former",
    "end": "2017.03.21",
    "img": true
   },
   {
    "id": "m0b1c433c03",
    "name": "雨宮舞夏",
    "kana": "あめみや まいか",
    "nick": "あめちゃん",
    "status": "former",
    "end": "2012.08.05",
    "img": true
   },
   {
    "id": "ma02405f9e4",
    "name": "梅田綾乃",
    "kana": "うめた あやの",
    "nick": "うめたん",
    "status": "former",
    "end": "2017.03.22",
    "img": true
   },
   {
    "id": "m45d221568d",
    "name": "大島涼花",
    "kana": "おおしま りょうか",
    "nick": "りょーちゃん",
    "status": "former",
    "end": "2017.06.08",
    "img": true
   },
   {
    "id": "m944e4a64ec",
    "name": "岡田彩花",
    "kana": "おかだ あやか",
    "nick": "あやか",
    "status": "former",
    "end": "2017.06.22",
    "img": true
   },
   {
    "id": "m5cbf2874a0",
    "name": "北汐莉",
    "kana": "きた しおり",
    "nick": "しおりーぬ",
    "status": "former",
    "end": "2012.08.05",
    "img": true
   },
   {
    "id": "mc0bfbc76de",
    "name": "北澤早紀",
    "kana": "きたざわ さき",
    "nick": "さっきー",
    "status": "former",
    "end": "2023.09.05",
    "img": true
   },
   {
    "id": "mfb9e430213",
    "name": "篠崎彩奈",
    "kana": "しのざき あやな",
    "nick": "あやなん",
    "status": "former",
    "end": "2024.02.10",
    "img": true
   },
   {
    "id": "m7791abaa76",
    "name": "髙島祐利奈",
    "kana": "たかしま ゆりな",
    "nick": "ゆーりん",
    "status": "former",
    "end": "2014.12.27",
    "img": true
   },
   {
    "id": "m4fa1f82b5f",
    "name": "長谷川晴奈",
    "kana": "はせがわ はるな",
    "nick": "はせはる",
    "status": "former",
    "end": "2012.08.05",
    "img": true
   },
   {
    "id": "m950bf00303",
    "name": "光宗薫",
    "kana": "みつむね かおる",
    "nick": "かおる",
    "status": "former",
    "end": "2012.10.24",
    "img": true
   },
   {
    "id": "m1563bd2d5c",
    "name": "村山彩希",
    "kana": "むらやま ゆいり",
    "nick": "ゆいりー",
    "status": "former",
    "end": "2025.06.15",
    "img": true
   },
   {
    "id": "m53dbbf233d",
    "name": "茂木忍",
    "kana": "もぎ しのぶ",
    "nick": "もぎちゃん",
    "status": "former",
    "end": "2024.01.19",
    "img": true
   },
   {
    "id": "md5230e8c4c",
    "name": "森山さくら",
    "kana": "もりやま さくら",
    "nick": "さくら",
    "status": "former",
    "end": "2012.08.05",
    "img": true
   },
   {
    "id": "m61e35aaad4",
    "name": "渡邊寧々",
    "kana": "わたなべ ねね",
    "nick": "ねねちゃん",
    "status": "former",
    "end": "2012.08.05",
    "img": true
   }
  ]
 },
 {
  "label": "14期生",
  "members": [
   {
    "id": "md18684a38e",
    "name": "内山奈月",
    "kana": "うちやま なつき",
    "nick": "なっきー",
    "status": "former",
    "end": "2016.02.21",
    "img": true
   },
   {
    "id": "m35d91e4bac",
    "name": "岡田奈々",
    "kana": "おかだ なな",
    "nick": "なぁちゃん",
    "status": "former",
    "end": "2023.04.02",
    "img": true
   },
   {
    "id": "m7c55824785",
    "name": "小嶋真子",
    "kana": "こじま まこ",
    "nick": "こじまこ",
    "status": "former",
    "end": "2019.05.12",
    "img": true
   },
   {
    "id": "m72e82c9d42",
    "name": "西野未姫",
    "kana": "にしの みき",
    "nick": "みきちゃん",
    "status": "former",
    "end": "2017.03.27",
    "img": true
   },
   {
    "id": "m3f5818963c",
    "name": "橋本耀",
    "kana": "はしもと ひかり",
    "nick": "ひかり",
    "status": "former",
    "end": "2015.08.09",
    "img": true
   },
   {
    "id": "mb37e43c270",
    "name": "前田美月",
    "kana": "まえだ みつき",
    "nick": "みつき",
    "status": "former",
    "end": "2015.08.09",
    "img": true
   }
  ]
 },
 {
  "label": "15期生",
  "members": [
   {
    "id": "m81dc04e6ca",
    "name": "福岡聖菜",
    "kana": "ふくおか せいな",
    "nick": "せいちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m2b8133cab8",
    "name": "飯野雅",
    "kana": "いいの みやび",
    "nick": "みやび",
    "status": "former",
    "end": "2018.01.22",
    "img": true
   },
   {
    "id": "m6ac406a688",
    "name": "市川愛美",
    "kana": "いちかわ まなみ",
    "nick": "まなみ",
    "status": "former",
    "end": "2023.08.31",
    "img": true
   },
   {
    "id": "mfe28e32b86",
    "name": "大川莉央",
    "kana": "おおかわ りお",
    "nick": "りおりおりん",
    "status": "former",
    "end": "2018.12.03",
    "img": true
   },
   {
    "id": "m4c50be2cbc",
    "name": "大和田南那",
    "kana": "おおわだ なな",
    "nick": "なーにゃ",
    "status": "former",
    "end": "2017.03.18",
    "img": true
   },
   {
    "id": "m77bcf92052",
    "name": "込山榛香",
    "kana": "こみやま はるか",
    "nick": "こみはる",
    "status": "former",
    "end": "2025.02.28",
    "img": true
   },
   {
    "id": "m8a08d6e601",
    "name": "佐藤妃星",
    "kana": "さとう きあら",
    "nick": "きぃちゃん",
    "status": "former",
    "end": "2023.09.17",
    "img": true
   },
   {
    "id": "m19312e4df4",
    "name": "達家真姫宝",
    "kana": "たつや まきほ",
    "nick": "まきちゃん",
    "status": "former",
    "end": "2020.12.11",
    "img": true
   },
   {
    "id": "md6d8c2e992",
    "name": "谷口めぐ",
    "kana": "たにぐち めぐ",
    "nick": "おめぐ",
    "status": "former",
    "end": "2024.05.30",
    "img": true
   },
   {
    "id": "macc7bd7194",
    "name": "土保瑞希",
    "kana": "つちやす みずき",
    "nick": "みずき",
    "status": "former",
    "end": "2015.08.09",
    "img": true
   },
   {
    "id": "m90c2f1fba9",
    "name": "向井地美音",
    "kana": "むかいち みおん",
    "nick": "みーおん",
    "status": "former",
    "end": "2026.04.30",
    "img": true
   },
   {
    "id": "mc65720ca04",
    "name": "湯本亜美",
    "kana": "ゆもと あみ",
    "nick": "あみちゃん",
    "status": "former",
    "end": "2023.10.30",
    "img": true
   }
  ]
 },
 {
  "label": "16期生",
  "members": [
   {
    "id": "meafb93c105",
    "name": "黒須遥香",
    "kana": "くろす はるか",
    "nick": "はーちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m7e6646935d",
    "name": "長友彩海",
    "kana": "ながとも あやみ",
    "nick": "あやみん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m3f376ef3f5",
    "name": "武藤小麟",
    "kana": "むとう おりん",
    "nick": "おりん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m27b7b8b37f",
    "name": "山内瑞葵",
    "kana": "やまうち みずき",
    "nick": "ずっきー",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m4d155730a5",
    "name": "山根涼羽",
    "kana": "やまね すずは",
    "nick": "ずんちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "meb690ce23d",
    "name": "浅井七海",
    "kana": "あさい ななみ",
    "nick": "なーみん",
    "status": "former",
    "end": "2024.01.31",
    "img": true
   },
   {
    "id": "m398025cbbd",
    "name": "稲垣香織",
    "kana": "いながき かおり",
    "nick": "かおり",
    "status": "former",
    "end": "2022.12.27",
    "img": true
   },
   {
    "id": "mb98cf0744b",
    "name": "梅本和泉",
    "kana": "うめもと いずみ",
    "nick": "いずみん",
    "status": "former",
    "end": "2018.11.25",
    "img": true
   },
   {
    "id": "m06601d2f2b",
    "name": "佐藤美波",
    "kana": "さとう みなみ",
    "nick": "さとみな",
    "status": "former",
    "end": "2024.07.01",
    "img": true
   },
   {
    "id": "m0897533d4e",
    "name": "庄司なぎさ",
    "kana": "しょうじ なぎさ",
    "nick": "なぎゅ",
    "status": "former",
    "end": "2018.11.04",
    "img": true
   },
   {
    "id": "mb99053e0ee",
    "name": "鈴木くるみ",
    "kana": "すずき くるみ",
    "nick": "くるるん",
    "status": "former",
    "end": "2026.05.15",
    "img": true
   },
   {
    "id": "m8eb55525b6",
    "name": "田口愛佳",
    "kana": "たぐち まなか",
    "nick": "まなか",
    "status": "former",
    "end": "2026.06.22",
    "img": true
   },
   {
    "id": "m5469c671b0",
    "name": "田屋美咲",
    "kana": "たや みさき",
    "nick": "たっちゃん",
    "status": "former",
    "end": "2019.04.07",
    "img": true
   },
   {
    "id": "maa73a3f344",
    "name": "野口菜々美",
    "kana": "のぐち ななみ",
    "nick": "ななちゃん",
    "status": "former",
    "end": "2017.03.31",
    "img": true
   },
   {
    "id": "md55d83823f",
    "name": "播磨七海",
    "kana": "はりま ななみ",
    "nick": "はりまちゃん",
    "status": "former",
    "end": "2019.05.11",
    "img": true
   },
   {
    "id": "m1e7575bee7",
    "name": "本間麻衣",
    "kana": "ほんま まい",
    "nick": "まいちゃん",
    "status": "former",
    "end": "2021.10.01",
    "img": true
   },
   {
    "id": "m8f43eea7c6",
    "name": "前田彩佳",
    "kana": "まえだ あやか",
    "nick": "あやか",
    "status": "former",
    "end": "2021.03.31",
    "img": true
   },
   {
    "id": "m81b300f50b",
    "name": "道枝咲",
    "kana": "みちえだ さき",
    "nick": "さきぽん",
    "status": "former",
    "end": "2023.09.14",
    "img": true
   },
   {
    "id": "mb68ae4a0b9",
    "name": "安田叶",
    "kana": "やすだ かな",
    "nick": "かなぶん",
    "status": "former",
    "end": "2022.03.25",
    "img": true
   }
  ]
 },
 {
  "label": "17期生",
  "members": [
   {
    "id": "mcf318a2f30",
    "name": "太田有紀",
    "kana": "おおた ゆき",
    "nick": "ゆきたん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "mae2455da9a",
    "name": "佐藤綺星",
    "kana": "さとう あいり",
    "nick": "あいちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m68a9bcd768",
    "name": "橋本恵理子",
    "kana": "はしもと えりこ",
    "nick": "えりちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m8ed36471c9",
    "name": "畠山希美",
    "kana": "はたけやま のぞみ",
    "nick": "のんちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "mee08b3cf44",
    "name": "平田侑希",
    "kana": "ひらた ゆき",
    "nick": "ゆき",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m03e8a353c4",
    "name": "布袋百椛",
    "kana": "ほてい もか",
    "nick": "ほてちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m2d71c3a4b3",
    "name": "正鋳真優",
    "kana": "まさい まゆう",
    "nick": "まゆうちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m1bc228eee7",
    "name": "水島美結",
    "kana": "みずしま みゆう",
    "nick": "みずみん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m0caa1f90e0",
    "name": "山﨑空",
    "kana": "やまざき そら",
    "nick": "そらら",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m12ecd653c7",
    "name": "小濱心音",
    "kana": "こはま ここね",
    "nick": "こっこ",
    "status": "former",
    "end": "2024.09.30",
    "img": true
   },
   {
    "id": "m955e8710ae",
    "name": "長谷川新奈",
    "kana": "はせがわ にいな",
    "nick": "にいなん",
    "status": "former",
    "end": "2022.08.28",
    "img": true
   }
  ]
 },
 {
  "label": "18期生",
  "members": [
   {
    "id": "m137f6ecae5",
    "name": "秋山由奈",
    "kana": "あきやま ゆな",
    "nick": "ゆなちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "md00833b3cc",
    "name": "新井彩永",
    "kana": "あらい さえ",
    "nick": "さえちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "mcc757b6219",
    "name": "工藤華純",
    "kana": "くどう かすみ",
    "nick": "かすみん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m2777d608ff",
    "name": "久保姫菜乃",
    "kana": "くぼ ひなの",
    "nick": "ちゃんひな",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m7620bbe8c0",
    "name": "迫由芽実",
    "kana": "さこ ゆめみ",
    "nick": "ゆめみん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m64754b10a3",
    "name": "成田香姫奈",
    "kana": "なりた こひな",
    "nick": "こひ",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "mcb63ed344b",
    "name": "八木愛月",
    "kana": "やぎ あづき",
    "nick": "あづ",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m208a4d50e5",
    "name": "山口結愛",
    "kana": "やまぐち ゆい",
    "nick": "ゆいち",
    "status": "current",
    "end": null,
    "img": true
   }
  ]
 },
 {
  "label": "19期生",
  "members": [
   {
    "id": "m5c50d10fc2",
    "name": "伊藤百花",
    "kana": "いとう ももか",
    "nick": "いともも",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m4c92a69891",
    "name": "奥本カイリ",
    "kana": "おくもと カイリ",
    "nick": "カイリ",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "mb9a2d02f83",
    "name": "川村結衣",
    "kana": "かわむら ゆい",
    "nick": "かわゆい",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m996b982826",
    "name": "白鳥沙怜",
    "kana": "しらとり さり",
    "nick": "さりい",
    "status": "former",
    "end": "2026.05.31",
    "img": true
   },
   {
    "id": "m4d248b8745",
    "name": "花田藍衣",
    "kana": "はなだ めい",
    "nick": "めいめい",
    "status": "former",
    "end": "2026.06.23",
    "img": true
   }
  ]
 },
 {
  "label": "20期生",
  "members": [
   {
    "id": "m950a4277cf",
    "name": "大賀彩姫",
    "kana": "おおが さき",
    "nick": "さーちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m771f0f18f9",
    "name": "近藤沙樹",
    "kana": "こんどう さき",
    "nick": "こさき",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m75afcf0782",
    "name": "丸山ひなた",
    "kana": "まるやま ひなた",
    "nick": "まるちゃん",
    "status": "current",
    "end": null,
    "img": true
   }
  ]
 },
 {
  "label": "21期生",
  "members": [
   {
    "id": "mc216906b48",
    "name": "髙橋舞桜",
    "kana": "たかはし まお",
    "nick": "まーたん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m733cb99255",
    "name": "田中沙友利",
    "kana": "たなか さゆり",
    "nick": "さゆりん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m8929e0ae47",
    "name": "牧戸愛茉",
    "kana": "まきと えま",
    "nick": "えまちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m03c28cbe77",
    "name": "森川優",
    "kana": "もりかわ ゆう",
    "nick": "ゆーゆ",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m1346102927",
    "name": "渡邉葵心",
    "kana": "わたなべ きこ",
    "nick": "きこちゃん",
    "status": "current",
    "end": null,
    "img": true
   }
  ]
 },
 {
  "label": "Team 8",
  "members": [
   {
    "id": "m19d40a15c4",
    "name": "小栗有以",
    "kana": "おぐり ゆい",
    "nick": "ゆいゆい",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "mf2496e22b5",
    "name": "行天優莉奈",
    "kana": "ぎょうてん ゆりな",
    "nick": "ゆりな",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "md02117a315",
    "name": "倉野尾成美",
    "kana": "くらのお なるみ",
    "nick": "なる",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m37b17cbad0",
    "name": "坂川陽香",
    "kana": "さかがわ ひゆか",
    "nick": "ひゆか",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m0a9fa0ff14",
    "name": "下尾みう",
    "kana": "したお みう",
    "nick": "みう",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m5c851365d1",
    "name": "髙橋彩音",
    "kana": "たかはし あやね",
    "nick": "あやねちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m1394a1e881",
    "name": "徳永羚海",
    "kana": "とくなが れみ",
    "nick": "れみたん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m24bea589ba",
    "name": "永野芹佳",
    "kana": "ながの せりか",
    "nick": "せりちゃん",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m36ee03d1c4",
    "name": "橋本陽菜",
    "kana": "はしもと はるな",
    "nick": "はるpyon",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "m05d4027597",
    "name": "阿部芽唯",
    "kana": "あべ めい",
    "nick": "めい",
    "status": "former",
    "end": "2017.08.20",
    "img": true
   },
   {
    "id": "mab1356c4af",
    "name": "伊藤きらら",
    "kana": "いとう きらら",
    "nick": "きらら",
    "status": "former",
    "end": "2019.08.12",
    "img": true
   },
   {
    "id": "m2f0c475cf6",
    "name": "井上美優",
    "kana": "いのうえ みゆう",
    "nick": "みゆこ",
    "status": "former",
    "end": "2020.09.24",
    "img": true
   },
   {
    "id": "md3b35fed86",
    "name": "岩﨑萌花",
    "kana": "いわさき もえか",
    "nick": "もえたん",
    "status": "former",
    "end": "2016.04.03",
    "img": true
   },
   {
    "id": "mb6b9f83daf",
    "name": "上見天乃",
    "kana": "うえみ そらの",
    "nick": "そらのん",
    "status": "former",
    "end": "2023.10.14",
    "img": true
   },
   {
    "id": "m3078df3afe",
    "name": "歌田初夏",
    "kana": "うただ はつか",
    "nick": "はっつ",
    "status": "former",
    "end": "2023.07.30",
    "img": true
   },
   {
    "id": "m438668b569",
    "name": "太田奈緒",
    "kana": "おおた なお",
    "nick": "なお",
    "status": "former",
    "end": "2019.12.20",
    "img": true
   },
   {
    "id": "mfc69884078",
    "name": "大西桃香",
    "kana": "おおにし ももか",
    "nick": "おおにし",
    "status": "former",
    "end": "2024.02.15",
    "img": true
   },
   {
    "id": "m5e42dcf5c4",
    "name": "岡部麟",
    "kana": "おかべ りん",
    "nick": "べりん",
    "status": "former",
    "end": "2024.04.04",
    "img": true
   },
   {
    "id": "m3ee04b03bc",
    "name": "奥原妃奈子",
    "kana": "おくはら ひなこ",
    "nick": "ひーな",
    "status": "former",
    "end": "2023.09.08",
    "img": true
   },
   {
    "id": "m7b6b10659e",
    "name": "奥洞千捺",
    "kana": "おくぼら ちなつ",
    "nick": "ちっぴ",
    "status": "former",
    "end": "2014.06.18",
    "img": true
   },
   {
    "id": "m38106da988",
    "name": "奥本陽菜",
    "kana": "おくもと ひなの",
    "nick": "のんのん",
    "status": "former",
    "end": "2022.03.24",
    "img": true
   },
   {
    "id": "m0613120e2e",
    "name": "小田えりな",
    "kana": "おだ えりな",
    "nick": "おだえり",
    "status": "former",
    "end": "2024.04.23",
    "img": true
   },
   {
    "id": "m85387ace90",
    "name": "尾上美月",
    "kana": "おのうえ みづき",
    "nick": "おみづき",
    "status": "former",
    "end": "2021.07.31",
    "img": true
   },
   {
    "id": "mf861d05b9f",
    "name": "蒲地志奈",
    "kana": "かまち ゆきな",
    "nick": "ゆっきーなゆきな",
    "status": "former",
    "end": "2021.06.30",
    "img": true
   },
   {
    "id": "m0c74e00a42",
    "name": "川原美咲",
    "kana": "かわはら みさき",
    "nick": "みっさー",
    "status": "former",
    "end": "2023.08.11",
    "img": true
   },
   {
    "id": "m6500046903",
    "name": "北玲名",
    "kana": "きた れいな",
    "nick": "れなな",
    "status": "former",
    "end": "2016.10.08",
    "img": true
   },
   {
    "id": "mdac51527b8",
    "name": "近藤萌恵里",
    "kana": "こんどう もえり",
    "nick": "もえりん",
    "status": "former",
    "end": "2016.10.08",
    "img": true
   },
   {
    "id": "m5c6ce69f8d",
    "name": "坂口渚沙",
    "kana": "さかぐち なぎさ",
    "nick": "なぎ",
    "status": "former",
    "end": "2023.08.05",
    "img": true
   },
   {
    "id": "m4d9e7a1bb3",
    "name": "佐藤朱",
    "kana": "さとう あかり",
    "nick": "あかりん",
    "status": "former",
    "end": "2021.03.29",
    "img": true
   },
   {
    "id": "mc65a4a0cd7",
    "name": "佐藤栞",
    "kana": "さとう しおり",
    "nick": "しおりん",
    "status": "former",
    "end": "2019.06.08",
    "img": true
   },
   {
    "id": "m4cee194e6d",
    "name": "佐藤七海",
    "kana": "さとう ななみ",
    "nick": "ななみん",
    "status": "former",
    "end": "2019.09.30",
    "img": true
   },
   {
    "id": "meb8147961d",
    "name": "塩原香凜",
    "kana": "しおばら かりん",
    "nick": "かりんりん",
    "status": "former",
    "end": "2020.09.24",
    "img": true
   },
   {
    "id": "mc30917a537",
    "name": "清水麻璃亜",
    "kana": "しみず まりあ",
    "nick": "まりあ",
    "status": "former",
    "end": "2023.08.01",
    "img": true
   },
   {
    "id": "mfda2d034d6",
    "name": "下青木香鈴",
    "kana": "しもあおき かりん",
    "nick": "かりん",
    "status": "former",
    "end": "2018.08.10",
    "img": true
   },
   {
    "id": "m768c157e61",
    "name": "鈴木優香",
    "kana": "すずき ゆうか",
    "nick": "ゆうかりん",
    "status": "former",
    "end": "2021.09.28",
    "img": true
   },
   {
    "id": "m08d57aac10",
    "name": "高岡薫",
    "kana": "たかおか かおる",
    "nick": "かおるんば",
    "status": "former",
    "end": "2023.08.29",
    "img": true
   },
   {
    "id": "m293d22a9ee",
    "name": "髙橋彩香",
    "kana": "たかはし さやか",
    "nick": "たかさやさやりん",
    "status": "former",
    "end": "2023.08.17",
    "img": true
   },
   {
    "id": "m7122cce6fe",
    "name": "谷優里",
    "kana": "たに ゆうり",
    "nick": "ゆぅりぃちゃんたーに",
    "status": "former",
    "end": "2017.06.24",
    "img": true
   },
   {
    "id": "m629571bc91",
    "name": "谷川聖",
    "kana": "たにかわ ひじり",
    "nick": "ひじりん",
    "status": "former",
    "end": "2019.05.31",
    "img": true
   },
   {
    "id": "m2777daebcc",
    "name": "長久玲奈",
    "kana": "ちょう くれな",
    "nick": "くれにゃん",
    "status": "former",
    "end": "2019.02.02",
    "img": true
   },
   {
    "id": "m23ff4761e5",
    "name": "寺田美咲",
    "kana": "てらだ みさき",
    "nick": "みさっきー",
    "status": "former",
    "end": "2019.10.22",
    "img": true
   },
   {
    "id": "m42587308e7",
    "name": "中野郁海",
    "kana": "なかの いくみ",
    "nick": "いくみん",
    "status": "former",
    "end": "2019.05.30",
    "img": true
   },
   {
    "id": "mc878b2d8bd",
    "name": "布谷梨琉",
    "kana": "ぬのや りる",
    "nick": "りる",
    "status": "former",
    "end": "2020.09.24",
    "img": true
   },
   {
    "id": "m98b52e46e2",
    "name": "野田陽菜乃",
    "kana": "のだ ひなの",
    "nick": "ひなのん",
    "status": "former",
    "end": "2019.05.05",
    "img": true
   },
   {
    "id": "m914bbcfc64",
    "name": "長谷川百々花",
    "kana": "はせがわ ももか",
    "nick": "はせもも",
    "status": "former",
    "end": "2021.03.26",
    "img": true
   },
   {
    "id": "m1d8c251a56",
    "name": "服部有菜",
    "kana": "はっとり ゆうな",
    "nick": "ゆうな",
    "status": "former",
    "end": "2023.05.31",
    "img": true
   },
   {
    "id": "m7820e4b38f",
    "name": "濵咲友菜",
    "kana": "はま さゆな",
    "nick": "はまちゃん",
    "status": "former",
    "end": "2023.04.30",
    "img": true
   },
   {
    "id": "maac0617920",
    "name": "濵松里緒菜",
    "kana": "はままつ りおな",
    "nick": "Riona",
    "status": "former",
    "end": "2017.07.02",
    "img": true
   },
   {
    "id": "m37f712372d",
    "name": "早坂つむぎ",
    "kana": "はやさか つむぎ",
    "nick": "つっちゃん",
    "status": "former",
    "end": "2018.04.20",
    "img": true
   },
   {
    "id": "m1e8cf7cab5",
    "name": "春本ゆき",
    "kana": "はるもと ゆき",
    "nick": "ゆき",
    "status": "former",
    "end": "2021.10.24",
    "img": true
   },
   {
    "id": "m36c062c28e",
    "name": "左伴彩佳",
    "kana": "ひだりとも あやか",
    "nick": "ひだあや",
    "status": "former",
    "end": "2023.07.31",
    "img": true
   },
   {
    "id": "m2029e2a3be",
    "name": "人見古都音",
    "kana": "ひとみ ことね",
    "nick": "こっちゃん",
    "status": "former",
    "end": "2019.05.20",
    "img": true
   },
   {
    "id": "m4804e7bc80",
    "name": "平野ひかる",
    "kana": "ひらの ひかる",
    "nick": "ひか",
    "status": "former",
    "end": "2023.04.30",
    "img": true
   },
   {
    "id": "m72e7be7927",
    "name": "廣瀬なつき",
    "kana": "ひろせ なつき",
    "nick": "なっちゃん",
    "status": "former",
    "end": "2018.03.04",
    "img": true
   },
   {
    "id": "m2a37684636",
    "name": "福地礼奈",
    "kana": "ふくち れな",
    "nick": "ぺな",
    "status": "former",
    "end": "2017.05.13",
    "img": true
   },
   {
    "id": "m5cb77069ff",
    "name": "福留光帆",
    "kana": "ふくとめ みつほ",
    "nick": "とめちゃんふくとめ",
    "status": "former",
    "end": "2022.07.31",
    "img": true
   },
   {
    "id": "m29d2e2789c",
    "name": "藤園麗",
    "kana": "ふじぞの れい",
    "nick": "れいちゃん",
    "status": "former",
    "end": "2023.05.17",
    "img": true
   },
   {
    "id": "ma3a321d90b",
    "name": "藤村菜月",
    "kana": "ふじむら なつき",
    "nick": "ナチュ",
    "status": "former",
    "end": "2016.04.03",
    "img": true
   },
   {
    "id": "mcbfff63300",
    "name": "本田仁美",
    "kana": "ほんだ ひとみ",
    "nick": "ひぃちゃん",
    "status": "former",
    "end": "2024.01.28",
    "img": true
   },
   {
    "id": "md865dbf7b1",
    "name": "松村美紅",
    "kana": "まつむら みく",
    "nick": "みっつん",
    "status": "former",
    "end": "2021.04.30",
    "img": true
   },
   {
    "id": "m07dd79f5b0",
    "name": "御供茉白",
    "kana": "みとも ましろ",
    "nick": "まっちゃん",
    "status": "former",
    "end": "2022.12.24",
    "img": true
   },
   {
    "id": "m8ee958912f",
    "name": "宮里莉羅",
    "kana": "みやざと りら",
    "nick": "らんりー",
    "status": "former",
    "end": "2021.07.28",
    "img": true
   },
   {
    "id": "mdfcf70eb5d",
    "name": "舞木香純",
    "kana": "もうぎ かすみ",
    "nick": "かすみん",
    "status": "former",
    "end": "2018.02.18",
    "img": true
   },
   {
    "id": "ma8668afc92",
    "name": "森脇由衣",
    "kana": "もりわき ゆい",
    "nick": "ゆいぴょんゆい",
    "status": "former",
    "end": "2015.01.26",
    "img": true
   },
   {
    "id": "m9350093282",
    "name": "谷口もか",
    "kana": "やぐち もか",
    "nick": "もか",
    "status": "former",
    "end": "2018.11.04",
    "img": true
   },
   {
    "id": "ma5514cad70",
    "name": "山田杏華",
    "kana": "やまだ きょうか",
    "nick": "きょうか",
    "status": "former",
    "end": "2023.12.26",
    "img": true
   },
   {
    "id": "m228973ad5c",
    "name": "山田菜々美",
    "kana": "やまだ ななみ",
    "nick": "山田",
    "status": "former",
    "end": "2019.06.22",
    "img": true
   },
   {
    "id": "mdc7dd8a9a7",
    "name": "山本亜依",
    "kana": "やまもと あい",
    "nick": "あいぽん",
    "status": "former",
    "end": "2016.05.07",
    "img": true
   },
   {
    "id": "m0abb909ec0",
    "name": "山本瑠香",
    "kana": "やまもと るか",
    "nick": "るか",
    "status": "former",
    "end": "2020.06.28",
    "img": true
   },
   {
    "id": "m97a685dd7a",
    "name": "横道侑里",
    "kana": "よこみち ゆり",
    "nick": "ゆり",
    "status": "former",
    "end": "2019.05.18",
    "img": true
   },
   {
    "id": "m4da7d3fd8b",
    "name": "横山結衣",
    "kana": "よこやま ゆい",
    "nick": "ヨコちゃん",
    "status": "former",
    "end": "2021.11.30",
    "img": true
   },
   {
    "id": "m8525db821b",
    "name": "吉川七瀬",
    "kana": "よしかわ ななせ",
    "nick": "ななせ",
    "status": "former",
    "end": "2023.08.24",
    "img": true
   },
   {
    "id": "m947093ecce",
    "name": "吉田華恋",
    "kana": "よしだ かれん",
    "nick": "かれん",
    "status": "former",
    "end": "2023.10.01",
    "img": true
   },
   {
    "id": "m23652ed514",
    "name": "吉野未優",
    "kana": "よしの みゆ",
    "nick": "みゆゆん",
    "status": "former",
    "end": "2017.01.29",
    "img": true
   },
   {
    "id": "mc610a251ee",
    "name": "立仙愛理",
    "kana": "りっせん あいり",
    "nick": "りっせん",
    "status": "former",
    "end": "2021.02.28",
    "img": true
   }
  ]
 },
 {
  "label": "选秀1期生",
  "members": [
   {
    "id": "m86451ea20e",
    "name": "川本紗矢",
    "kana": "かわもと さや",
    "nick": "さやや",
    "status": "former",
    "end": "2020.08.31",
    "img": true
   },
   {
    "id": "m4c18c5adcc",
    "name": "後藤萌咲",
    "kana": "ごとう もえ",
    "nick": "もえきゅん",
    "status": "former",
    "end": "2019.08.13",
    "img": true
   },
   {
    "id": "mb63ec1f618",
    "name": "下口ひなな",
    "kana": "しもぐち ひなな",
    "nick": "ひなな",
    "status": "former",
    "end": "2024.02.25",
    "img": true
   },
   {
    "id": "m0556a0cd38",
    "name": "田北香世子",
    "kana": "たきた かよこ",
    "nick": "かよよん",
    "status": "former",
    "end": "2022.02.27",
    "img": true
   },
   {
    "id": "ma137b68bb2",
    "name": "西山怜那",
    "kana": "にしやま れな",
    "nick": "れなりんにっすぃー",
    "status": "former",
    "end": "2015.12.23",
    "img": true
   },
   {
    "id": "m1995c4d64f",
    "name": "横島亜衿",
    "kana": "よこしま あえり",
    "nick": "あえりん",
    "status": "former",
    "end": "2017.06.05",
    "img": true
   }
  ]
 },
 {
  "label": "选秀2期生",
  "members": [
   {
    "id": "m3132fa46f7",
    "name": "千葉恵里",
    "kana": "ちば えりい",
    "nick": "えりい",
    "status": "current",
    "end": null,
    "img": true
   },
   {
    "id": "me83953715f",
    "name": "久保怜音",
    "kana": "くぼ さとね",
    "nick": "さとぴー",
    "status": "former",
    "end": "2022.03.28",
    "img": true
   },
   {
    "id": "m57c7f27296",
    "name": "高橋希良",
    "kana": "たかはし きら",
    "nick": "きらりん",
    "status": "former",
    "end": "2017.04.11",
    "img": true
   },
   {
    "id": "m8211748c25",
    "name": "西川怜",
    "kana": "にしかわ れい",
    "nick": "れい",
    "status": "former",
    "end": "2022.03.30",
    "img": true
   },
   {
    "id": "m7fd10d121d",
    "name": "野村奈央",
    "kana": "のむら なお",
    "nick": "なお",
    "status": "former",
    "end": "2017.08.13",
    "img": true
   },
   {
    "id": "md120e9f609",
    "name": "樋渡結依",
    "kana": "ひわたし ゆい",
    "nick": "ひーわたん",
    "status": "former",
    "end": "2019.11.28",
    "img": true
   },
   {
    "id": "m8842552071",
    "name": "山邊歩夢",
    "kana": "やまべ あゆ",
    "nick": "あゆ",
    "status": "former",
    "end": "2023.10.28",
    "img": true
   }
  ]
 },
 {
  "label": "选秀3期生",
  "members": [
   {
    "id": "m893ac9bb29",
    "name": "石綿星南",
    "kana": "いしわた せな",
    "nick": "せなたん",
    "status": "former",
    "end": "2023.08.07",
    "img": true
   },
   {
    "id": "m042d895d17",
    "name": "大竹ひとみ",
    "kana": "おおたけ ひとみ",
    "nick": "ちゃけ",
    "status": "former",
    "end": "2024.01.21",
    "img": true
   },
   {
    "id": "m1f9f0db40e",
    "name": "大盛真歩",
    "kana": "おおもり まほ",
    "nick": "まほぴょん",
    "status": "former",
    "end": "2026.06.30",
    "img": true
   },
   {
    "id": "m33ceaac8d3",
    "name": "岡田梨奈",
    "kana": "おかだ りな",
    "nick": "おかりな",
    "status": "former",
    "end": "2023.10.31",
    "img": true
   },
   {
    "id": "mb69551eff4",
    "name": "勝又彩央里",
    "kana": "かつまた さおり",
    "nick": "さおりん",
    "status": "former",
    "end": "2019.06.28",
    "img": true
   },
   {
    "id": "m6eae1770eb",
    "name": "神山莉穂",
    "kana": "かみやま りほ",
    "nick": "りーたん",
    "status": "former",
    "end": "2018.10.20",
    "img": true
   },
   {
    "id": "m718a9a4060",
    "name": "蔵本美結",
    "kana": "くらもと みゆう",
    "nick": "くららみゆう",
    "status": "former",
    "end": "2022.03.23",
    "img": true
   },
   {
    "id": "md832d2445a",
    "name": "小林蘭",
    "kana": "こばやし らん",
    "nick": "らんちゃんらんたん",
    "status": "former",
    "end": "2023.05.21",
    "img": true
   },
   {
    "id": "md374ff1e25",
    "name": "齋藤陽菜",
    "kana": "さいとう はるな",
    "nick": "はーたん",
    "status": "former",
    "end": "2024.01.10",
    "img": true
   },
   {
    "id": "m5919976d23",
    "name": "佐藤詩識",
    "kana": "さとう しおり",
    "nick": "しおり",
    "status": "former",
    "end": "2019.11.27",
    "img": true
   },
   {
    "id": "m387e8eb718",
    "name": "末永祐月",
    "kana": "すえなが ゆづき",
    "nick": "ゆづちゃん",
    "status": "former",
    "end": "2020.11.30",
    "img": true
   },
   {
    "id": "m342ef1aaee",
    "name": "多田京加",
    "kana": "ただ きょうか",
    "nick": "きょうかきょん多田先輩",
    "status": "former",
    "end": "2023.09.10",
    "img": true
   },
   {
    "id": "m94f141d642",
    "name": "永野恵",
    "kana": "ながの めぐみ",
    "nick": "めぐみん",
    "status": "former",
    "end": "2023.03.22",
    "img": true
   },
   {
    "id": "me8e1c8a1bf",
    "name": "原澤音妃",
    "kana": "はらさわ おとひ",
    "nick": "おと",
    "status": "former",
    "end": "2018.08.22",
    "img": true
   },
   {
    "id": "m34b9363a96",
    "name": "古川夏凪",
    "kana": "ふるかわ なづな",
    "nick": "なづなん古川",
    "status": "former",
    "end": "2022.03.21",
    "img": true
   },
   {
    "id": "m2497883f96",
    "name": "本田そら",
    "kana": "ほんだ そら",
    "nick": "そらちゃん",
    "status": "former",
    "end": "2021.05.27",
    "img": true
   },
   {
    "id": "m4d05d322be",
    "name": "矢作萌夏",
    "kana": "やはぎ もえか",
    "nick": "もえちゃんふくちゃんもんたもえかはぎもえもえにゃ",
    "status": "former",
    "end": "2020.02.04",
    "img": true
   },
   {
    "id": "m863c3c49cf",
    "name": "吉橋柚花",
    "kana": "よしはし ゆずか",
    "nick": "ゆず",
    "status": "former",
    "end": "2023.12.29",
    "img": true
   }
  ]
 },
 {
  "label": "兼任・移籍加入",
  "members": [
   {
    "id": "m1a9960888b",
    "name": "生駒里奈",
    "kana": "いこま りな",
    "nick": "いこたん",
    "status": "former",
    "end": "2015.05.14",
    "img": true,
    "note": "乃木坂46 1期"
   },
   {
    "id": "m63dbf0d545",
    "name": "石田安奈",
    "kana": "いしだ あんな",
    "nick": "あんにゃ",
    "status": "former",
    "end": "2013.04.28",
    "img": true,
    "note": "SKE48 2期"
   },
   {
    "id": "m13807e9202",
    "name": "小笠原茉由",
    "kana": "おがさわら まゆ",
    "nick": "まーちゅん",
    "status": "former",
    "end": "2016.12.24",
    "img": true,
    "note": "NMB48 1期"
   },
   {
    "id": "ma6fda0b37c",
    "name": "木﨑ゆりあ",
    "kana": "きざき ゆりあ",
    "nick": "ゆりあ",
    "status": "former",
    "end": "2017.09.30",
    "img": true,
    "note": "SKE48 3期"
   },
   {
    "id": "m85354e3ac1",
    "name": "北川綾巴",
    "kana": "きたがわ りょうは",
    "nick": "りょうは",
    "status": "former",
    "end": "2018.04.02",
    "img": true,
    "note": "SKE48 6期"
   },
   {
    "id": "m0b301c1439",
    "name": "小谷里歩",
    "kana": "こたに りほ",
    "nick": "りぽぽ",
    "status": "former",
    "end": "2015.05.28",
    "img": true,
    "note": "NMB48 1期"
   },
   {
    "id": "m1ddbc69337",
    "name": "兒玉遥",
    "kana": "こだま はるか",
    "nick": "はるっぴ",
    "status": "former",
    "end": "2018.04.02",
    "img": true,
    "note": "HKT48 1期"
   },
   {
    "id": "maee3c0e1b5",
    "name": "渋谷凪咲",
    "kana": "しぶや なぎさ",
    "nick": "なぎさ",
    "status": "former",
    "end": "2018.04.02",
    "img": true,
    "note": "NMB48 4期"
   },
   {
    "id": "me6fb3762c8",
    "name": "白間美瑠",
    "kana": "しろま みる",
    "nick": "みるるん",
    "status": "former",
    "end": "2018.04.02",
    "img": true,
    "note": "NMB48 1期"
   },
   {
    "id": "m7019a2a212",
    "name": "朝長美桜",
    "kana": "ともなが みお",
    "nick": "みお",
    "status": "former",
    "end": "2018.04.02",
    "img": true,
    "note": "HKT48 2期"
   },
   {
    "id": "mb1e792ec04",
    "name": "中西智代梨",
    "kana": "なかにし ちより",
    "nick": "ちょり",
    "status": "former",
    "end": "2023.08.28",
    "img": true,
    "note": "HKT48 1期"
   },
   {
    "id": "meef0b581c1",
    "name": "野澤玲奈",
    "kana": "のざわ れな",
    "nick": "レナチャン",
    "status": "former",
    "end": "2019.05.06",
    "img": true,
    "note": "JKT48 1期"
   },
   {
    "id": "mbd7c543a96",
    "name": "古畑奈和",
    "kana": "ふるはた なお",
    "nick": "なお",
    "status": "former",
    "end": "2015.05.29",
    "img": true,
    "note": "SKE48 5期"
   },
   {
    "id": "m2267bb69ab",
    "name": "松井珠理奈",
    "kana": "まつい じゅりな",
    "nick": "じゅりな",
    "status": "former",
    "end": "2015.12.24",
    "img": true,
    "note": "SKE48 1期"
   },
   {
    "id": "mb259d958cc",
    "name": "宮脇咲良",
    "kana": "みやわき さくら",
    "nick": "さくら",
    "status": "former",
    "end": "2018.04.02",
    "img": true,
    "note": "HKT48 1期"
   },
   {
    "id": "m9d465977d5",
    "name": "矢倉楓子",
    "kana": "やぐら ふうこ",
    "nick": "ふぅちゃん",
    "status": "former",
    "end": "2015.05.29",
    "img": true,
    "note": "NMB48 2期"
   },
   {
    "id": "m032ade677c",
    "name": "矢吹奈子",
    "kana": "やぶき なこ",
    "nick": "なこ",
    "status": "former",
    "end": "2018.04.02",
    "img": true,
    "note": "HKT48 3期"
   },
   {
    "id": "m6fdb66051f",
    "name": "山本彩",
    "kana": "やまもと さやか",
    "nick": "さやか",
    "status": "former",
    "end": "2016.05.26",
    "img": true,
    "note": "NMB48 1期"
   },
   {
    "id": "mc7423da6e7",
    "name": "渡辺美優紀",
    "kana": "わたなべ みゆき",
    "nick": "みるきー",
    "status": "former",
    "end": "2016.08.09",
    "img": true,
    "note": "NMB48 1期"
   },
   {
    "id": "m0755eef18b",
    "name": "Stefi",
    "kana": "ステフィ",
    "nick": "",
    "status": "former",
    "end": "2018.10.15",
    "img": true,
    "note": "JKT48 3期"
   },
   {
    "id": "m87d17f4624",
    "name": "Mobile",
    "kana": "モバイル",
    "nick": "",
    "status": "former",
    "end": "2018.10.15",
    "img": true,
    "note": "BNK48 1期"
   }
  ]
 },
 {
  "label": "其他",
  "members": [
   {
    "id": "m3a1066424d",
    "name": "繁藤冬佳",
    "kana": "しげふじ ふゆか",
    "nick": "しげふー",
    "status": "former",
    "end": "2016.08.10",
    "img": true,
    "note": "ぱるる選抜"
   },
   {
    "id": "mc45d8c3879",
    "name": "塚本まり子",
    "kana": "つかもと まりこ",
    "nick": "まりり",
    "status": "former",
    "end": "2014.09.01",
    "img": true,
    "note": "大人AKB48"
   },
   {
    "id": "m737be25b9a",
    "name": "日出有香",
    "kana": "ひので ゆか",
    "nick": "ゆかりん",
    "status": "former",
    "end": "2016.08.10",
    "img": true,
    "note": "ぱるる選抜"
   },
   {
    "id": "m500e29d3df",
    "name": "馬嘉伶",
    "kana": "マ・チャリン",
    "nick": "まちゃりん",
    "status": "former",
    "end": "2024.02.20",
    "img": true,
    "note": "台湾研究生"
   }
  ]
 }
];
